### ISSUE TITLE
unmasked source images

### ISSUE THREAD

**Issue by k-sokolov** [czarmanu/photi-lakeice-dataset#1]
Hi, first thanks for releasing a great dataset. From all the pictures, there is only one folder where input images are not masked, in others there are black areas everywhere except the lake. Did you consider releasing full input images for other training pairs as well?

**Comment by czarmanu** [comment]
This dataset focuses primarily on the ice monitoring application on the lake pixels. Hence, we masked out the background pixels for majority of the cameras (except Sihl cam2, winter 2016-17). At the moment, we do not plan to release the full input images.
